name: CI

on:
  push:
    branches:
      - main  # Define which branches trigger this workflow

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the operating system for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Action to set up Python

        with:
          python-version: 3.9  # Define your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project dependencies

      - name: Run tests
        run: |
          pytest  # Command to run your tests

      - name: Lint code
        run: |
          pylint src  # Command to lint your code
