name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'         # Trigger on changes within the src directory
      - 'utils/**'       # Trigger on changes within the utils directory
      - 'tests/**'       # Trigger on changes within the tests directory
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'         # Trigger on changes within the src directory
      - 'utils/**'       # Trigger on changes within the utils directory
      - 'tests/**'       # Trigger on changes within the tests directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings
