name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'         # Trigger on changes within the src directory
      - 'utils/**'       # Trigger on changes within the utils directory
      - 'tests/**'       # Trigger on changes within the tests directory
      - '.github/workflows/ci.yml'  # Trigger on changes to the ci.yml file
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'         # Trigger on changes within the src directory
      - 'utils/**'       # Trigger on changes within the utils directory
      - 'tests/**'       # Trigger on changes within the tests directory
      - '.github/workflows/ci.yml'  # Trigger on changes to the ci.yml file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv

      - name: Set up virtual environment
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest --maxfail=5 --disable-warnings
